version: "3.9"

services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: Docker/MySQL/Dockerfile
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

  app:
    container_name: app
    build:
      context: .
      dockerfile: Docker/Django/Dockerfile
    volumes:
      - ./Django_App:/code
      - ./static:/static
    ports:
      - "8000:8000"
    command:  bash -c "python manage.py collectstatic --noinput && \
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./.env
    links:
      - db
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  db_data:
  static: