# Generated by Django 3.2.16 on 2022-11-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blearn_app', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
