# Generated by Django 3.2.16 on 2022-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blearn_app', '0004_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='new_content',
            field=models.TextField(null=True),
        ),
    ]
