# Generated by Django 3.2.16 on 2022-11-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blearn_app', '0006_alter_content_new_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='new_content',
            field=models.TextField(null=True),
        ),
    ]
